name: parse-import-seed build and deploy

on:
  push:
    branches:
      - main
      - fix/ci

env:
  DEPLOY_BRANCH: parse-import-seed-compiled

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install
      working-directory: ./parse-import-seed

    - name: Build TypeScript
      run: npm run build
      working-directory: ./parse-import-seed

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'auto-publish'
        git config --global user.email 'auto-publish@nabu.io'
        git fetch
        if git rev-parse --verify --quiet ${{ env.DEPLOY_BRANCH }}; then
          git checkout ${{ env.DEPLOY_BRANCH }}
        else
          git checkout -b ${{ env.DEPLOY_BRANCH }}
        fi
        git add -f ./parse-import-seed/dist
        git commit -m "Auto-publish to GitHub Pages"
        git push origin ${{ env.DEPLOY_BRANCH }} --force
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
